name: caldenservice
description: "Servicio tecnico Calden"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.1
  flutter_blue_plus: ^1.34.5
  easy_refresh: ^3.4.0
  wifi_scan: ^0.4.1+1
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.6
  flutter_native_splash: ^2.0.4

icons_launcher:
  image_path: "assets/LogoApp.png"
  platforms:
    ios:
      enable: true
      image_path: "assets/LogoApp.png"
    android:
      enable: true
      image_path: "assets/LogoApp.png"
      adaptive_background_image: "assets/Background.png"
      adaptive_foreground_image: "assets/Foreground.png"

flutter_native_splash:
  color: "#302b36"
  image: assets/Foreground.png
  android: true
  ios: true


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
